language: java

sudo: false

jdk:
  - openjdk7

notifications:
  email: false

before_script:

  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  # The following did not work reliable
  # - sudo service mysql stop
  # - sudo service postgresql stop

  # Ensure Gradle wrapper is executable
  - chmod +x gradlew

script:
  - ./gradlew clean assemble test

